[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Agent", "Mistral", "Model", "Provider"]
license = ["Apache-2.0"]
name = "ai.model.provider.mistral"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.model.provider.mistral"
version = "@toml.version@"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.model.provider.mistral-native"
version = "@toml.version@"
path = "../native/build/libs/ai.model.provider.mistral-native-@project.version@.jar"

[[dependency]]
org = "ballerina"
name = "ai"
version = "1.0.1"
repository="local"
